// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-adminCenter/internal/logic/adminservice"
	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-adminCenter/internal/svc"
	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-adminCenter/pb/admin"
)

type AdminServiceServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServiceServer
}

func NewAdminServiceServer(svcCtx *svc.ServiceContext) *AdminServiceServer {
	return &AdminServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServiceServer) LogOn(ctx context.Context, in *admin.LogOnRequest) (*admin.LogOnResponse, error) {
	l := adminservicelogic.NewLogOnLogic(ctx, s.svcCtx)
	return l.LogOn(in)
}

func (s *AdminServiceServer) RefreshToken(ctx context.Context, in *admin.RefreshTokenRequest) (*admin.RefreshTokenResponse, error) {
	l := adminservicelogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *AdminServiceServer) GetAdminMenuList(ctx context.Context, in *admin.GetAdminMenuListRequest) (*admin.GetAdminMenuListResponse, error) {
	l := adminservicelogic.NewGetAdminMenuListLogic(ctx, s.svcCtx)
	return l.GetAdminMenuList(in)
}
