// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-adminCenter/internal/logic/operationlogservice"
	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-adminCenter/internal/svc"
	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-adminCenter/pb/admin"
)

type OperationLogServiceServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedOperationLogServiceServer
}

func NewOperationLogServiceServer(svcCtx *svc.ServiceContext) *OperationLogServiceServer {
	return &OperationLogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OperationLogServiceServer) AddOperationLog(ctx context.Context, in *admin.AddOperationLogRequest) (*admin.Empty, error) {
	l := operationlogservicelogic.NewAddOperationLogLogic(ctx, s.svcCtx)
	return l.AddOperationLog(in)
}

func (s *OperationLogServiceServer) UpdateOperationLog(ctx context.Context, in *admin.UpdateOperationLogRequest) (*admin.Empty, error) {
	l := operationlogservicelogic.NewUpdateOperationLogLogic(ctx, s.svcCtx)
	return l.UpdateOperationLog(in)
}
